apiVersion: v1
baseDomain: %%LAB_DOMAIN%%
metadata:
  name: %%CLUSTER_NAME%%
networking:
  networkType: OpenShiftSDN
  clusterNetwork:
  - cidr: 10.100.0.0/14 
    hostPrefix: 23 
  serviceNetwork: 
  - 172.30.0.0/16
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 3
platform:
  none: {}
pullSecret: '%%PULL_SECRET%%'
sshKey: %%SSH_KEY%%
additionalTrustBundle: |

imageContentSources:
- mirrors:
  - nexus.%%LAB_DOMAIN%%:5001/origin
  source: %%OKD_SOURCE_1%%
- mirrors:
  - nexus.%%LAB_DOMAIN%%:5001/origin
  source: %%OKD_SOURCE_2%%
